-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE deadstock.attribute_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9-]+$'::text),
  parent_id uuid,
  level integer DEFAULT 0 CHECK (level >= 0 AND level <= 3),
  path text,
  display_order integer DEFAULT 0,
  icon text,
  color text,
  description text,
  is_active boolean DEFAULT true,
  is_searchable boolean DEFAULT true,
  is_required boolean DEFAULT false,
  translations jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT attribute_categories_pkey PRIMARY KEY (id),
  CONSTRAINT attribute_categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES deadstock.attribute_categories(id)
);
CREATE TABLE deadstock.board_elements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  board_id uuid NOT NULL,
  zone_id uuid,
  element_type text NOT NULL CHECK (element_type = ANY (ARRAY['textile'::text, 'palette'::text, 'inspiration'::text, 'calculation'::text, 'note'::text, 'video'::text, 'link'::text, 'pdf'::text, 'pattern'::text, 'silhouette'::text])),
  element_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  position_x double precision NOT NULL DEFAULT 0,
  position_y double precision NOT NULL DEFAULT 0,
  width double precision,
  height double precision,
  z_index integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT board_elements_pkey PRIMARY KEY (id),
  CONSTRAINT board_elements_board_id_fkey FOREIGN KEY (board_id) REFERENCES deadstock.boards(id),
  CONSTRAINT board_elements_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES deadstock.board_zones(id)
);
CREATE TABLE deadstock.board_zones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  board_id uuid NOT NULL,
  name text NOT NULL DEFAULT 'Nouvelle zone'::text,
  color text DEFAULT '#E5E7EB'::text,
  position_x double precision NOT NULL DEFAULT 0,
  position_y double precision NOT NULL DEFAULT 0,
  width double precision NOT NULL DEFAULT 400,
  height double precision NOT NULL DEFAULT 300,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  crystallized_at timestamp with time zone,
  linked_project_id uuid,
  CONSTRAINT board_zones_pkey PRIMARY KEY (id),
  CONSTRAINT board_zones_board_id_fkey FOREIGN KEY (board_id) REFERENCES deadstock.boards(id),
  CONSTRAINT board_zones_linked_project_id_fkey FOREIGN KEY (linked_project_id) REFERENCES deadstock.projects(id)
);
CREATE TABLE deadstock.boards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  session_id text,
  name text,
  description text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'archived'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT boards_pkey PRIMARY KEY (id),
  CONSTRAINT boards_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE deadstock.dictionary_mappings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid NOT NULL,
  source_term text NOT NULL,
  source_locale text NOT NULL CHECK (source_locale = ANY (ARRAY['fr'::text, 'en'::text, 'es'::text, 'it'::text])),
  translations jsonb NOT NULL,
  confidence numeric DEFAULT 1.0 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  source text DEFAULT 'manual'::text CHECK (source = ANY (ARRAY['manual'::text, 'llm_suggested'::text, 'user_feedback'::text])),
  usage_count integer DEFAULT 0 CHECK (usage_count >= 0),
  validated_at timestamp with time zone,
  validated_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dictionary_mappings_pkey PRIMARY KEY (id),
  CONSTRAINT dictionary_mappings_category_id_fkey FOREIGN KEY (category_id) REFERENCES deadstock.attribute_categories(id)
);
CREATE TABLE deadstock.discovery_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  status text DEFAULT 'queued'::text,
  mode text DEFAULT 'batch'::text,
  sites_total integer DEFAULT 0,
  sites_completed integer DEFAULT 0,
  sites_failed integer DEFAULT 0,
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  config jsonb,
  error_summary jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT discovery_jobs_pkey PRIMARY KEY (id)
);
CREATE TABLE deadstock.favorites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text NOT NULL,
  textile_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT favorites_pkey PRIMARY KEY (id),
  CONSTRAINT favorites_textile_id_fkey FOREIGN KEY (textile_id) REFERENCES deadstock.textiles(id)
);
CREATE TABLE deadstock.imported_patterns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  session_id text,
  name text NOT NULL,
  brand text,
  garment_type text,
  file_url text,
  file_type text CHECK (file_type = ANY (ARRAY['pdf'::text, 'image'::text])),
  file_size_bytes integer,
  page_count integer,
  analysis_result jsonb,
  precision_level integer CHECK (precision_level = ANY (ARRAY[1, 2, 3])),
  confidence double precision CHECK (confidence >= 0::double precision AND confidence <= 1::double precision),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT imported_patterns_pkey PRIMARY KEY (id),
  CONSTRAINT imported_patterns_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE deadstock.llm_cost_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  date date NOT NULL,
  category text,
  calls_count integer DEFAULT 0,
  total_cost double precision DEFAULT 0,
  avg_confidence double precision,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT llm_cost_tracking_pkey PRIMARY KEY (id)
);
CREATE TABLE deadstock.normalization_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp without time zone DEFAULT now(),
  dictionary_version text NOT NULL,
  total_textiles integer NOT NULL,
  changes_detected integer DEFAULT 0,
  changes_detail jsonb,
  applied boolean DEFAULT false,
  applied_at timestamp without time zone,
  applied_by uuid,
  notes text,
  CONSTRAINT normalization_snapshots_pkey PRIMARY KEY (id)
);
CREATE TABLE deadstock.projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  session_id text,
  name text NOT NULL,
  name_i18n jsonb DEFAULT '{}'::jsonb,
  description text,
  description_i18n jsonb DEFAULT '{}'::jsonb,
  project_type text NOT NULL DEFAULT 'single_piece'::text CHECK (project_type = ANY (ARRAY['single_piece'::text, 'collection'::text, 'prototype'::text])),
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'in_progress'::text, 'completed'::text, 'archived'::text])),
  current_step text NOT NULL DEFAULT 'idea'::text CHECK (current_step = ANY (ARRAY['idea'::text, 'inspiration'::text, 'design'::text, 'calculate'::text, 'sourcing'::text, 'validation'::text, 'purchase'::text, 'production'::text, 'impact'::text])),
  mood_board jsonb DEFAULT '[]'::jsonb,
  color_palette jsonb,
  style_keywords ARRAY DEFAULT '{}'::text[],
  reference_images jsonb DEFAULT '[]'::jsonb,
  garments jsonb DEFAULT '[]'::jsonb,
  fabric_width integer DEFAULT 140 CHECK (fabric_width >= 50 AND fabric_width <= 300),
  margin_percent integer DEFAULT 10 CHECK (margin_percent >= 0 AND margin_percent <= 50),
  fabric_modifiers jsonb DEFAULT '{"velvet": false, "stretch": false, "directional": false, "patternMatch": false}'::jsonb,
  total_yardage numeric,
  yardage_details jsonb,
  selected_textiles jsonb DEFAULT '[]'::jsonb,
  client_name text,
  client_email text,
  deadline date,
  budget_min numeric,
  budget_max numeric,
  currency text DEFAULT 'EUR'::text,
  constraints jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  source_board_id uuid,
  source_zone_id uuid,
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT projects_source_board_id_fkey FOREIGN KEY (source_board_id) REFERENCES deadstock.boards(id),
  CONSTRAINT projects_source_zone_id_fkey FOREIGN KEY (source_zone_id) REFERENCES deadstock.board_zones(id)
);
CREATE TABLE deadstock.scraping_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL,
  profile_id uuid,
  status text DEFAULT 'queued'::text,
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  config jsonb,
  products_fetched integer DEFAULT 0,
  products_saved integer DEFAULT 0,
  products_skipped integer DEFAULT 0,
  products_updated integer DEFAULT 0,
  errors_count integer DEFAULT 0,
  quality_score numeric,
  logs jsonb,
  error_details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scraping_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT scraping_jobs_site_id_fkey FOREIGN KEY (site_id) REFERENCES deadstock.sites(id),
  CONSTRAINT scraping_jobs_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES deadstock.site_profiles(id)
);
CREATE TABLE deadstock.scraping_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_platform text NOT NULL,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  status text NOT NULL CHECK (status = ANY (ARRAY['running'::text, 'completed'::text, 'failed'::text, 'partial'::text])),
  items_found integer DEFAULT 0,
  items_new integer DEFAULT 0,
  items_updated integer DEFAULT 0,
  items_failed integer DEFAULT 0,
  error_message text,
  error_details jsonb,
  duration_seconds integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT scraping_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE deadstock.site_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL,
  discovered_at timestamp with time zone DEFAULT now(),
  valid_until timestamp with time zone NOT NULL,
  profile_version integer DEFAULT 1,
  collections jsonb,
  sample_products jsonb,
  data_structure jsonb,
  quality_metrics jsonb,
  recommendations jsonb,
  is_shopify boolean DEFAULT true,
  total_collections integer,
  relevant_collections integer,
  estimated_products integer,
  needs_rediscovery boolean DEFAULT false,
  rediscovery_reason text,
  created_at timestamp with time zone DEFAULT now(),
  estimated_available integer DEFAULT 0,
  global_analysis jsonb DEFAULT '{}'::jsonb,
  extraction_patterns jsonb DEFAULT '{"patterns": [], "analyzedAt": null, "productsAnalyzed": 0}'::jsonb,
  sale_type_detection jsonb,
  CONSTRAINT site_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT site_profiles_site_id_fkey FOREIGN KEY (site_id) REFERENCES deadstock.sites(id)
);
CREATE TABLE deadstock.sites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  url text NOT NULL UNIQUE,
  name text,
  platform_type text DEFAULT 'shopify'::text,
  status text DEFAULT 'new'::text,
  priority text DEFAULT 'medium'::text,
  discovery_completed_at timestamp with time zone,
  last_scraped_at timestamp with time zone,
  scraping_config jsonb,
  quality_score numeric,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  source_locale text NOT NULL DEFAULT 'fr'::text CHECK (source_locale = ANY (ARRAY['fr'::text, 'en'::text, 'es'::text, 'it'::text, 'de'::text])),
  CONSTRAINT sites_pkey PRIMARY KEY (id)
);
CREATE TABLE deadstock.textile_attributes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  textile_id uuid NOT NULL,
  category_id uuid NOT NULL,
  value text NOT NULL,
  source_term text,
  source_locale text,
  confidence double precision DEFAULT 1.0 CHECK (confidence >= 0::double precision AND confidence <= 1::double precision),
  category_slug text NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT textile_attributes_pkey PRIMARY KEY (id),
  CONSTRAINT textile_attributes_textile_id_fkey FOREIGN KEY (textile_id) REFERENCES deadstock.textiles(id),
  CONSTRAINT textile_attributes_category_id_fkey FOREIGN KEY (category_id) REFERENCES deadstock.attribute_categories(id)
);
CREATE TABLE deadstock.textiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  scraped_at timestamp with time zone NOT NULL DEFAULT now(),
  available boolean NOT NULL DEFAULT true,
  name text NOT NULL,
  description text,
  material_type text,
  composition jsonb,
  color text,
  pattern text,
  quantity_value numeric NOT NULL,
  quantity_unit text NOT NULL,
  minimum_order_value numeric,
  minimum_order_unit text,
  price_value numeric,
  price_currency text DEFAULT 'EUR'::text,
  price_per_unit numeric,
  price_per_unit_label text,
  source_platform text NOT NULL,
  source_url text NOT NULL UNIQUE,
  source_product_id text,
  supplier_name text,
  supplier_location text,
  supplier_url text,
  image_url text,
  additional_images ARRAY,
  width_value numeric,
  width_unit text,
  weight_value numeric,
  weight_unit text,
  certifications ARRAY,
  raw_data jsonb,
  data_quality_score integer DEFAULT 50 CHECK (data_quality_score >= 0 AND data_quality_score <= 100),
  missing_fields ARRAY,
  material_id uuid,
  supplier_id uuid,
  search_vector tsvector DEFAULT (((setweight(to_tsvector('french'::regconfig, COALESCE(name, ''::text)), 'A'::"char") || setweight(to_tsvector('french'::regconfig, COALESCE(description, ''::text)), 'B'::"char")) || setweight(to_tsvector('french'::regconfig, COALESCE(material_type, ''::text)), 'A'::"char")) || setweight(to_tsvector('french'::regconfig, COALESCE(color, ''::text)), 'C'::"char")),
  name_i18n jsonb,
  description_i18n jsonb,
  currency character varying DEFAULT 'EUR'::character varying,
  material_original text,
  color_original text,
  pattern_original text,
  tags_original ARRAY,
  material_confidence numeric CHECK (material_confidence >= 0::numeric AND material_confidence <= 1::numeric),
  color_confidence numeric CHECK (color_confidence >= 0::numeric AND color_confidence <= 1::numeric),
  pattern_confidence numeric CHECK (pattern_confidence >= 0::numeric AND pattern_confidence <= 1::numeric),
  needs_review boolean DEFAULT false,
  review_reasons jsonb,
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  site_id uuid,
  sale_type character varying DEFAULT 'unknown'::character varying CHECK (sale_type::text = ANY (ARRAY['fixed_length'::character varying, 'cut_to_order'::character varying, 'hybrid'::character varying, 'by_piece'::character varying, 'unknown'::character varying]::text[])),
  price_per_meter numeric,
  CONSTRAINT textiles_pkey PRIMARY KEY (id),
  CONSTRAINT textiles_site_id_fkey FOREIGN KEY (site_id) REFERENCES deadstock.sites(id)
);
CREATE TABLE deadstock.unknown_terms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  term text NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['fiber'::text, 'color'::text, 'pattern'::text, 'weave'::text])),
  source_platform text,
  occurrences integer DEFAULT 1,
  first_seen_at timestamp without time zone DEFAULT now(),
  last_seen_at timestamp without time zone DEFAULT now(),
  contexts jsonb DEFAULT '[]'::jsonb,
  llm_suggestion text,
  llm_confidence double precision,
  llm_reasoning text,
  llm_cost_total double precision DEFAULT 0,
  llm_calls_count integer DEFAULT 0,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'reviewing'::text, 'approved'::text, 'rejected'::text, 'skipped'::text])),
  human_mapping text,
  is_regex boolean DEFAULT false,
  regex_pattern text,
  reviewed_by uuid,
  reviewed_at timestamp without time zone,
  review_notes text,
  added_to_dict boolean DEFAULT false,
  added_to_dict_at timestamp without time zone,
  dict_type text CHECK (dict_type = ANY (ARRAY['exact'::text, 'regex'::text, NULL::text])),
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT unknown_terms_pkey PRIMARY KEY (id)
);
CREATE TABLE deadstock.user_favorites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  textile_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_favorites_pkey PRIMARY KEY (id),
  CONSTRAINT user_favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_favorites_textile_id_fkey FOREIGN KEY (textile_id) REFERENCES deadstock.textiles(id)
);
CREATE TABLE deadstock.users (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text,
  role text NOT NULL DEFAULT 'free'::text CHECK (role = ANY (ARRAY['free'::text, 'premium'::text, 'pro'::text, 'admin'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  searches_today integer NOT NULL DEFAULT 0,
  searches_reset_at date NOT NULL DEFAULT CURRENT_DATE,
  live_searches_today integer NOT NULL DEFAULT 0,
  avatar_url text,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
