ALTER TABLE deadstock.users
ADD COLUMN IF NOT EXISTS searches_today INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS searches_reset_at DATE NOT NULL DEFAULT CURRENT_DATE,
ADD COLUMN IF NOT EXISTS live_searches_today INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS avatar_url TEXT;
